package com.example.lettersidebar;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CONSTACT_BEAN".
*/
public class ConstactBeanDao extends AbstractDao<ConstactBean, Long> {

    public static final String TABLENAME = "CONSTACT_BEAN";

    /**
     * Properties of entity ConstactBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Memo = new Property(1, String.class, "memo", false, "MEMO");
        public final static Property Account_name = new Property(2, String.class, "account_name", false, "ACCOUNT_NAME");
        public final static Property Memo_py = new Property(3, String.class, "memo_py", false, "MEMO_PY");
    }


    public ConstactBeanDao(DaoConfig config) {
        super(config);
    }
    
    public ConstactBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CONSTACT_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"MEMO\" TEXT," + // 1: memo
                "\"ACCOUNT_NAME\" TEXT," + // 2: account_name
                "\"MEMO_PY\" TEXT);"); // 3: memo_py
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CONSTACT_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ConstactBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String memo = entity.getMemo();
        if (memo != null) {
            stmt.bindString(2, memo);
        }
 
        String account_name = entity.getAccount_name();
        if (account_name != null) {
            stmt.bindString(3, account_name);
        }
 
        String memo_py = entity.getMemo_py();
        if (memo_py != null) {
            stmt.bindString(4, memo_py);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ConstactBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String memo = entity.getMemo();
        if (memo != null) {
            stmt.bindString(2, memo);
        }
 
        String account_name = entity.getAccount_name();
        if (account_name != null) {
            stmt.bindString(3, account_name);
        }
 
        String memo_py = entity.getMemo_py();
        if (memo_py != null) {
            stmt.bindString(4, memo_py);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ConstactBean readEntity(Cursor cursor, int offset) {
        ConstactBean entity = new ConstactBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // memo
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // account_name
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // memo_py
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ConstactBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMemo(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setAccount_name(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setMemo_py(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ConstactBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ConstactBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ConstactBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
